[package]
name = "foreign-instruments"
version = "0.0.1"
authors = ["styyle14"]

[dependencies]
futures = "*"
libusb = "*"
crossbeam = "*"
tokio = "*"

[[bin]]
name = "foreigninstrumentsd"
path = "src/main.rs"
