[package]
name = "foreign-instruments"
version = "0.0.1"
authors = ["styyle14"]

[dependencies]
lazy_static = "1.2.0"
libusb = "0.3"
crossbeam = "0.6"

[lib]
name = "foreigninstruments"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "foreigninstrumentsd"
path = "src/main.rs"
